name: Terraform EC2 Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform en subdirectorio
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AWS EC2 t2.micro

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # cambia esto si usas otra región

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   if: github.ref == 'refs/heads/main'
